name: CI

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  tflint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [prod]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.56.0

      - name: Show TFLint version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint --format compact --recursive

  fmt-validate-plan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [prod]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.2

      - name: Setup google service account - ${{ matrix.env }}
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets[format('GCP_CREDENTIALS_{0}', matrix.env)] }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -recursive -check

      - name: Terraform Init - ${{ matrix.env }}
        id: init
        run: terraform init -input=false
        working-directory: ${{ github.workspace }}/${{ matrix.env }}

      - name: Terraform Validate - ${{ matrix.env }}
        id: validate
        run: terraform validate
        working-directory: ${{ github.workspace }}/${{ matrix.env }}

      - name: Terraform Plan - ${{ matrix.env }}
        id: plan
        run: terraform plan -input=false -out=plan.out
        working-directory: ${{ github.workspace }}/${{ matrix.env }}

      - name: Comment Plan - ${{ matrix.env }}
        uses: borchero/terraform-plan-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          planfile: plan.out
          header: 📝 Terraform Plan
          working-directory: ${{ github.workspace }}/${{ matrix.env }}